### ISSUE TITLE
Add static tariffs

### ISSUE THREAD

**Issue by Xilt** [zigul/HomeAssistant-CEZdistribuce#14]
[](Would it be possible to equip sensor with static tariffs according to [https://www.cezdistribuce.cz/webpublic/file/edee/distribuce/cezdistribuce_pasmaplatnostintavt_prubehove_mereni.pdf?](url)

My new setup now uses static tariff **AKU8V1** and I would very much welcome to use the same sensor in HA rather then devising new one and redo all the automatons around it.

**Comment by Wraydroth** [comment]
I have same request - at very similar situation that I am now having PVT1. If would be possible to add just manual option to add the tariff or reflect those static ones. It would be really helpfull to be able to use the integration again after change of the tariff.

**Comment by lukasde** [comment]
I also vote for this request. I have EVV2. Thank you very much! Lukas

**Comment by Lipown** [comment]
Same here, i have EVV3. Or is there another solution?

**Comment by pokornyIt** [comment]
Hi all, for static traffic you can use the standard HA Scheduler helper very effectively. It can be set graphically or using the configuration in the configuration YAML file.

```yaml
schedules:
     bathroom_schedule:
         name: TRV - Static TRV start/stop
         icon: mdi:thermometer-check
         monday:
           - from: "06:30:00"
             it: "08:30:00"
         tuesday:
           - from: "06:30:00"
             it: "08:30:00"
         wednesday:
           - from: "06:30:00"
             it: "08:30:00"
         thursday:
           - from: "06:30:00"
             it: "08:30:00"
         friday:
           - from: "06:30:00"
             it: "08:30:00"
```

Automation example:

```yaml
alias: TRV - bathroom scheduler
description: ""
trigger:
  - platform: state
    entity_id:
      - schedule.bathroom_schedule
    to: "on"
    id: TRV Start
  - platform: state
    entity_id:
      - schedule.bathroom_schedule
    to: "off"
    id: TRV Stop
action:
  - choose:
      - conditions:
          - condition: trigger
            id: TRV Start
        sequence:
          - service: climate.set_temperature
            data:
              temperature: "{{ states('input_number.trv_bathroom_temperature_high') }}"
            target:
              entity_id: climate.aqara_srt_e1_05
      - conditions:
          - condition: trigger
            id: TRV Stop
        sequence:
          - service: climate.set_temperature
            data:
              temperature: "{{ states('input_number.trv_bathroom_temperature_low') }}"
            target:
              entity_id: climate.aqara_srt_e1_05
mode: single
```
