### ISSUE TITLE
Průběhová měření (FVE)

### ISSUE THREAD

**Issue by rpelant** [zigul/HomeAssistant-CEZdistribuce#23]
Pro odběratele, kteří mají průběhové měření jsou časy spínání nízkého tarifu dané napevno, přepíná to elektroměr a ne HDO, podle této tabulky. https://www.cezdistribuce.cz/webpublic/file/edee/distribuce/cezdistribuce_pasmaplatnostintavt_prubehove_mereni.pdf
Ideální by bylo, kdyby to poskytoval datově web Čez distribuce ve stejném formátu, ale mohla by také tato komponenta pro úplnost mít zabudované konstatní odpovědi s tímto klíčem (viz. PDF)  Např. pro kód "AKU16V1" by to místo requestu vrátilo předpřipravená data s definicí časových rozsahů.
Průběhových měření přibývá, a HDO v FVE je použito na odpojování elektrárny.

**Comment by matomatusov** [comment]
Myslím, že by to byla dobrá věc, doplnit do dané integrace. Hlavně pro majitele FVE.
https://www.cezdistribuce.cz/cs/pro-zakazniky/spinani-hdo/casy-spinani.

**Comment by pokornyIt** [comment]
Statické hodnoty nastavíte snadno standadními prostředky HA viz: https://github.com/zigul/HomeAssistant-CEZdistribuce/issues/14#issuecomment-1913163575

**Comment by pokornyIt** [comment]
Protože se uvedený požadavek šíří jako požár, zak jsou tyto kódy přidány do aplikace.

**Comment by matomatusov** [comment]
@pokornyIt 
treba mať v configuration.yaml definovaný aj region? Alebo stači len Code: napr. EVV1.

**Comment by pokornyIt** [comment]
Je potřeba i region, jedno který z povolených

**Comment by matomatusov** [comment]
Takže platí tento vzor.

```

 Example configuration.yaml entry for showing current HDO state
binary_sensor:
  - platform: cezdistribuce
    name: nizky tarif
    region: stred
    code:  napr. EVV1
```

Super práce
Dik moc
