### ISSUE TITLE
[Bug]: Problém s časy pro EVV1

### ISSUE THREAD

**Issue by pokornyIt** [zigul/HomeAssistant-CEZdistribuce#32]
### Zkontrolujte existující problémy

- [X] Completed

### Verze

0.4.9

### Popište chybu / popiště kroky k reprodukci chyby

detail  https://github.com/zigul/HomeAssistant-CEZdistribuce/issues/23#issuecomment-2016820742

**Comment by pokornyIt** [comment]
Test config:
 ```yaml
  - platform: cezdistribuce
    name: stred_aku8v1
    region: stred
    code: AKU8V1
  - platform: cezdistribuce
    name: stred_aku8v2
    region: stred
    code: AKU8V2
  - platform: cezdistribuce
    name: stred_aku8v3
    region: stred
    code: AKU8V3
  - platform: cezdistribuce
    name: stred_aku8v4
    region: stred
    code: AKU8V4
  - platform: cezdistribuce
    name: stred_aku8v5
    region: stred
    code: AKU8V5
  - platform: cezdistribuce
    name: stred_aku8v6
    region: stred
    code: AKU8V6

  - platform: cezdistribuce
    name: stred_emov1
    region: stred
    code: EMOV1

  - platform: cezdistribuce
    name: stred_aku16v1
    region: stred
    code: AKU16V1

  - platform: cezdistribuce
    name: stred_ptv1
    region: stred
    code: PTV1
  - platform: cezdistribuce
    name: stred_ptv2
    region: stred
    code: PTV2
  - platform: cezdistribuce
    name: stred_ptv3
    region: stred
    code: PTV3
  - platform: cezdistribuce
    name: stred_ptv4
    region: stred
    code: PTV4

  - platform: cezdistribuce
    name: stred_evv1
    region: stred
    code: EVV1
  - platform: cezdistribuce
    name: stred_evv2
    region: stred
    code: EVV2
  - platform: cezdistribuce
    name: stred_evv3
    region: stred
    code: EVV3

  - platform: cezdistribuce
    name: stred_tcv1
    region: stred
    code: TCV1

  - platform: cezdistribuce
    name: stred_chlv1
    region: stred
    code: CHLV1
  - platform: cezdistribuce
    name: stred_chlv2
    region: stred
    code: CHLV2
  - platform: cezdistribuce
    name: stred_chlv3
    region: stred
    code: CHLV3
  - platform: cezdistribuce
    name: stred_chlv4
    region: stred
    code: CHLV4

  - platform: cezdistribuce
    name: stred_zav1
    region: stred
    code: ZAV1
  - platform: cezdistribuce
    name: stred_zav2
    region: stred
    code: ZAV2

  - platform: cezdistribuce
    name: stred_vikv1
    region: stred
    code: VIKV1

  - platform: cezdistribuce
    name: stred_vyrv1
    region: stred
    code: VYRV1
  - platform: cezdistribuce
    name: stred_vyrv2
    region: stred
    code: VYRV2
  - platform: cezdistribuce
    name: stred_vyrv3
    region: stred
    code: VYRV3
```

Dashboard:

```yaml
views:
  - title: Home
    cards:
      - type: history-graph
        entities:
          - entity: binary_sensor.stred_aku8v1
          - entity: binary_sensor.stred_aku8v2
          - entity: binary_sensor.stred_aku8v3
          - entity: binary_sensor.stred_aku8v4
          - entity: binary_sensor.stred_aku8v5
          - entity: binary_sensor.stred_aku8v6
          - entity: binary_sensor.stred_aku16v1
        hours_to_show: 28
        title: AKU8 / AKU16
      - type: history-graph
        entities:
          - entity: binary_sensor.stred_ptv1
          - entity: binary_sensor.stred_ptv2
          - entity: binary_sensor.stred_ptv3
          - entity: binary_sensor.stred_emov1
        hours_to_show: 28
        title: PTV / EMOV
      - type: history-graph
        entities:
          - entity: schedule.evv1
          - entity: binary_sensor.stred_evv1
          - entity: binary_sensor.stred_evv2
          - entity: binary_sensor.stred_evv3
          - entity: binary_sensor.stred_tcv1
        hours_to_show: 28
        title: EVV1 / TCV1
      - type: history-graph
        entities:
          - entity: binary_sensor.stred_chlv1
          - entity: binary_sensor.stred_chlv2
          - entity: binary_sensor.stred_chlv3
          - entity: binary_sensor.stred_chlv4
        hours_to_show: 28
        title: CHLV
      - type: history-graph
        entities:
          - entity: binary_sensor.stred_zav1
          - entity: binary_sensor.stred_zav2
          - entity: binary_sensor.stred_vikv1
          - entity: binary_sensor.stred_vyrv1
          - entity: binary_sensor.stred_vyrv2
          - entity: binary_sensor.stred_vyrv3
        hours_to_show: 28
        title: ZAV / VIKV / VYRV
```
