### ISSUE TITLE
Další spínaný tarif

### ISSUE THREAD

**Issue by Ladiikkk** [zigul/HomeAssistant-CEZdistribuce#38]
### Zkontrolujte existující požadavky

- [X] Completed

### Popište řešení, které chcete

Chtěl bych využívat další spínání času - druhý sensor podle jiného povelu z čezu. Je to možné?

**Comment by pokornyIt** [comment]
Pěkný den, ano je to možné. Stačí jen přidat další senzor, dle tohoto příkladu:

```yaml
binary_sensor:
  - platform: cezdistribuce
    name: stred_aku8v1
    region: stred
    code: AKU8V1
  - platform: cezdistribuce
    name: stred_aku8v2
    region: stred
    code: AKU8V2
  - platform: cezdistribuce
    name: stred_aku8v3
    region: stred
    code: AKU8V3
  - platform: cezdistribuce
    name: stred_aku8v4
    region: stred
    code: AKU8V4
  - platform: cezdistribuce
    name: stred_aku8v5
    region: stred
    code: AKU8V5
  - platform: cezdistribuce
    name: stred_aku8v6
    region: stred
    code: AKU8V6
```

Následně je možné vytvořit například tento historický graf:

```yaml
type: history-graph
entities:
  - entity: binary_sensor.stred_aku8v1
  - entity: binary_sensor.stred_aku8v2
  - entity: binary_sensor.stred_aku8v3
  - entity: binary_sensor.stred_aku8v4
  - entity: binary_sensor.stred_aku8v5
  - entity: binary_sensor.stred_aku8v6
hours_to_show: 28
title: AKU8
```
