### ISSUE TITLE
[Bug]: EMOV1 časy špatně

### ISSUE THREAD

**Issue by czechdude** [zigul/HomeAssistant-CEZdistribuce#40]
### Zkontrolujte existující problémy

- [x] Completed

### Verze

0.4.9

### Popište chybu / popiště kroky k reprodukci chyby

jen upozornění, že časy pro HDO EMOV1 jsou opsané z pdf špatně. je to 20-23:59 a 2-6

**Comment by pokornyIt** [comment]
Přiznám se, že aktuálně nemám dostatek čase na věnování se tomuto problému. 
Jako náhradní řešení je snadné použít standardní Schedule helper v Homeassistant.

**Comment by pokornyIt** [comment]
Pro jednoduchost stačí tohle přidat do configuration.yaml v HA (či upravit dle potřeb) a vše je krásně funkční, bez potřeby integrace.

```yaml
schedule:
  evv1:
    name: "EVV1"
    monday:
      - from: "00:00:00"
        to: "06:00:00"
      - from: "07:00:00"
        to: "09:00:00"
      - from: "10:00:00"
        to: "13:00:00"
      - from: "14:00:00"
        to: "16:00:00"
      - from: "17:00:00"
        to: "00:00:00"
    tuesday:
      - from: "00:00:00"
        to: "06:00:00"
      - from: "07:00:00"
        to: "09:00:00"
      - from: "10:00:00"
        to: "13:00:00"
      - from: "14:00:00"
        to: "16:00:00"
      - from: "17:00:00"
        to: "00:00:00"
    wednesday:
      - from: "00:00:00"
        to: "06:00:00"
      - from: "07:00:00"
        to: "09:00:00"
      - from: "10:00:00"
        to: "13:00:00"
      - from: "14:00:00"
        to: "16:00:00"
      - from: "17:00:00"
        to: "00:00:00"
    thursday:
      - from: "00:00:00"
        to: "06:00:00"
      - from: "07:00:00"
        to: "09:00:00"
      - from: "10:00:00"
        to: "13:00:00"
      - from: "14:00:00"
        to: "16:00:00"
      - from: "17:00:00"
        to: "00:00:00"
    friday:
      - from: "00:00:00"
        to: "06:00:00"
      - from: "07:00:00"
        to: "09:00:00"
      - from: "10:00:00"
        to: "13:00:00"
      - from: "14:00:00"
        to: "16:00:00"
      - from: "17:00:00"
        to: "00:00:00"
    saturday:
      - from: "00:00:00"
        to: "06:00:00"
      - from: "07:00:00"
        to: "09:00:00"
      - from: "10:00:00"
        to: "13:00:00"
      - from: "14:00:00"
        to: "16:00:00"
      - from: "17:00:00"
        to: "00:00:00"
    sunday:
      - from: "00:00:00"
        to: "06:00:00"
      - from: "07:00:00"
        to: "09:00:00"
      - from: "10:00:00"
        to: "13:00:00"
      - from: "14:00:00"
        to: "16:00:00"
      - from: "17:00:00"
        to: "00:00:00"
```
