### ISSUE TITLE
Status not provided

### ISSUE THREAD

**Issue by tomas-kulhanek** [zigul/HomeAssistant-CEZdistribuce#45]
### Zkontrolujte existující problémy

- [x] Completed

### Verze

0.5.0

### Napište svůj dotaz nebo s čím potřebujete pomoci

In the binary sensor state I have that has not been provided. What am I doing wrong? 

<img width="1469" alt="Image" src="https://github.com/user-attachments/assets/ddc0286f-ce97-409d-9e30-d1c336f07a95" />

```yaml
- platform: cezdistribuce
  name: stred_a3b6dp01
  region: stred
  code: A3B6DP01
- platform: cezdistribuce
  name: stred_a3b6dp02
  region: stred
  code: A3B6DP02
- platform: cezdistribuce
  name: stred_a3b6dp06
  region: stred
  code: A3B6DP06
```

## Čez distribuce

<img width="281" alt="Image" src="https://github.com/user-attachments/assets/67296c91-a588-4390-8de0-1a398a786363" />

## Muj Čez
<img width="374" alt="Image" src="https://github.com/user-attachments/assets/77942b6c-6824-4c21-ab48-e581fa252bba" />
